server:
  port: 8080
spring:
  application:
    name: demo-service
  rabbitmq:
    host: 192.168.0.108
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        prefetch: 1
    virtual-host: /

queues:
  testQueueName: testQueueName
  testQueueExchangeName: testQueueExchangeName
  testExchangeEnabled: true

# 指定日志配置文件
logging:
  config: D:\JavaProject\Demo\src\main\resources\logback-spring.xml